name: Publish Docker Image
on:
  push:
    tags:        
      - '*'
    branches:
      - debug

env:
  DOCKER_USER: ${{secrets.DOCKER_USER}}
  DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
  REPO_NAME: ${{secrets.REPO_NAME}}
  WIREGUARD_PRIVATE_KEY1: ${{ secrets.WIREGUARD_PRIVATE_KEY1 }}
  WIREGUARD_PRIVATE_KEY2: ${{ secrets.WIREGUARD_PRIVATE_KEY2 }}
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - docker_file: Dockerfile
            platforms: linux/arm64,linux/amd64
            private_key: 1
          - docker_file: Dockerfile.gpu
            tag_extension: -gpu
            platforms: linux/amd64
            private_key: 2
    steps:
    
    - run: sudo apt install wireguard
      
    - run: echo "${{secrets.WIREGUARD_PRIVATE_KEY1 }}" > privatekey
      if: ${{ matrix.private_key }}==1
    - run: echo "${{ secrets.WIREGUARD_PRIVATE_KEY2 }}" > privatekey
      if: ${{ matrix.private_key }}==2
    - run: sudo ip link add dev wg0 type wireguard

    - run: sudo ip address add dev wg0 192.168.1.2 peer 192.168.1.1

    - run: sudo wg set wg0 listen-port 48123 private-key privatekey peer SXfPBCndWGjBC3JYjxi3alt3XN0AzlndmHD9C7W4bUk= allowed-ips 0.0.0.0/0 endpoint ${{ secrets.ENDPOINT }}

    - run: sudo ip link set up dev wg0

    - run: curl -vvv http://192.168.1.1

    
    - name: Checkout
      uses: actions/checkout@v3
    - name: Free up disk space
      run: |
        sudo rm -rf /usr/share/dotnet
        sudo rm -rf /opt/ghc
        sudo rm -rf "/usr/local/share/boost"
        sudo rm -rf "$AGENT_TOOLSDIRECTORY"    
    # - name: Tailscale
    #   uses: tailscale/github-action@v4
    #   with:
    #     oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
    #     oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
    #     tags: tag:ci
        # args: up --exit-node=raspberrypi
        # exit-node: raspberrypi
        # args: "--exit-node=raspberrypi"
        # use-sudo: false
    # - name: Tailscale - ReRun Up Command To Set ExitNode to pfsense
    #   uses: tailscale/github-action@v4
    #   with:
    #     oauth-client-id: ${{ secrets.TS_OAUTH_CLIENTID }}
    #     oauth-secret: ${{ secrets.TS_OAUTH_SECRET  }}
    #     tags: tag:ci
    #     args: "--exit-node=raspberrypi"
    # - name: use named exit node in tailscale
    #   run: |
    #     timeout 1m sudo -E tailscale set --exit-node=raspberrypi

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build and Publish the Docker debug image
      if: github.ref == 'refs/heads/debug'
      run: |
        DOCKER_IMAGE_DEBUG=$DOCKER_USER/$REPO_NAME:debug${{ matrix.tag_extension }}
        docker buildx build . --no-cache --platform=${{ matrix.platforms }} -t "${DOCKER_IMAGE_DEBUG}" -f ${{ matrix.docker_file }} --push
    - name: Build and Publish the Docker image
      if: github.ref != 'refs/heads/debug'
      run: |
        DOCKER_IMAGE_LATEST=$DOCKER_USER/$REPO_NAME:latest${{ matrix.tag_extension }}
        DOCKER_IMAGE_VERSION=$DOCKER_USER/$REPO_NAME:$GITHUB_REF_NAME${{ matrix.tag_extension }}
        docker buildx build . --no-cache --platform=${{ matrix.platforms }} -t "${DOCKER_IMAGE_LATEST}" -t "${DOCKER_IMAGE_VERSION}" -f ${{ matrix.docker_file }} --push
